# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e513a2cb6796d9efb10115e0e89f59293eeb60faf4254ab0e25f3d8beb90543df599d38351f0478a920ac92fb1a951013beb14556d86c1296b4a4005606d027a

test:
  secret_key_base: c2bb1c96b360fe44b1a096eb775005f74085391b44d2a336e82a681506a12063ea547652c69b954ce78d32c0db83c082fb1047cab9a7078aa60f5849f7986e8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
